version: '3.5'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: app_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/certs
      - ./conf/locals.conf:/etc/nginx/conf.d/locals.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - network

#Docker Networks
networks:
  network:
    name: proxy_network
    driver: bridge
